# NETWORK
HEADER = {"User-Agent": "algosdk"}

ALGOD_ADDRESS = "https://mainnet-api.algonode.cloud"
INDEXER_ADDRESS = "https://mainnet-idx.algonode.cloud"

TEST_ALGOD_ADDRESS = "https://testnet-api.algonode.cloud"
TEST_INDEXER_ADDRESS = "https://testnet-idx.algonode.cloud"

MAX_CONNECTION_ATTEMPTS = 10
CONNECTION_ATTEMPT_DELAY_SEC = 2


# ADDRESSES
REWARDS_POOL = "737777777777777777777777777777777777777777777777777UFEJ2CI"

# ALGOREAM
ALGOREALM_FIRST_BLOCK = 13578170
ALGOREALM_APP_ID = 137491307
CROWN_ID = 137493252
SCEPTRE_ID = 137494385
ALGOREALM_LAW_BYTECODE = (
    "AiAIAwbr5sdBAQSE9sdB8f7HQegHJgEg/v////////////////////////////////////"
    "////8yBCISMwAQIxIzABgkEhAQMwEQJRIzAQAzAAASEDMBBygSEBAzAhAhBBIzAhQzAQAS"
    "EDMCESEFEjMCESEGEhEQMwISJRIQMwIBIQcOEDMCFTIDEhAzAiAyAxIQEA=="
)

# TEST ALGOREALM
TEST_ALGOREALM_FIRST_BLOCK = 14739865
TEST_ALGOREALM_APP_ID = 16258432
TEST_CROWN_ID = 16258490
TEST_SCEPTRE_ID = 16258497
TEST_ALGOREALM_LAW_BYTECODE = (
    "AiAIAwaAq+AHAQS6q+AHwavgB+gHJgEg/v////////////////////////////////////"
    "////8yBCISMwAQIxIQMwAYJBIQMwEQJRIQMwAAMwEAEhAzAQcoEhAzAhAhBBIQMwIUMwEA"
    "EhAzAhEhBRIzAhEhBhIREDMCEiUSEDMCASEHDhAzAhUyAxIQMwIgMgMSEA=="
)

# ALGOREALM CARD
ROYALTY_PERC = 5
ALGOREALM_CARD_FIRST_BLOCK = 16250000
CARD_ID = 321172366
ROYALTY_COLLECTOR_1 = "H7N65NZIWBOKFDSRNPLLDGN72HVFKXT4RRSY7M66B6Y2PFLQFKLPLHU5JU"
ROYALTY_COLLECTOR_2 = "2PDM3E7WLVPMEKCCMNTHM3FCZNZM4CSJQUOC4SWHMFPAR3N4NXBLCQKHPE"
CARD_CONTRACT_BYTECODE = (
    "AyAOAQMGBOgHnq6WmQGE9sdB8f7HQQVkjueSmQGQ6d8HAM7i0wcmAwtBc2FBbW91bnRFcS"
    "A/2+63KLBcoo5Ra9axmb/R6lVefIxlj7PeD7GnlXAqliDTxs2T9l1ewihCY2Z2bKLLcs4K"
    "SYUcLkrHYV4I7bxtwjIEIhJAAaIyBCMSQAD4MgQkEkAAAQAzABAkEjMBECQSEDMCECISED"
    "MDECISEDMEECISEDMFECUSEDMFASEEDhAzBSAyAxIQMwUVMgMSEDMAGCEFEjcAGgAoEhA3"
    "ABwBMwAAEhA3ADAAIQYSEDcAGgEiFhIQEDMBGCEFEjcBGgAoEhA3ARwBMwEAEhA3ATAAIQ"
    "cSEDcBGgEiFhIQEDMAADMCBxIQMwEAMwIHEhAzAgAzBRQSEDMDADMCBxIQMwMHKRIQMwQA"
    "MwIHEhAzBAcqEhAzAwgzBAgSEDMDCDMCCCEICyEJCg8QMwURIQoSEDMFEiISEDMFEzMCBx"
    "IQMwUUMwIAEhBCANczABAkEjMBECQSEDMCECUSEDMCASEEDhAzAiAyAxIQMwIVMgMSEDMA"
    "GCEFEjcAGgAoEhA3ABwBMwAAEhA3ADAAIQYSEDcAGgEiFhIQEDMBGCEFEjcBGgAoEhA3AR"
    "wBMwEAEhA3ATAAIQcSEDcBGgEiFhIQEDMAADMCFBIQMwEAMwIUEhAzAgIhCw0QMwIRIQoS"
    "EDMCEiISEDMCADMCExIQQgA0MRAlEjEBIQQOEDETMgMSEDEVMgMSEDEgMgMSEDERIQoSED"
    "ESIQwSEDEAMRQSEDEEIQ0MEA=="
)

# TEST ALGOREALM CARD
TEST_ROYALTY_COLLECTOR_1 = "KKXHB5C4QMGQJ4WZQRRXGD7SJF5AKUUJ635U3SNBYKA6IILSJ6YVX2NQQU"
TEST_ROYALTY_COLLECTOR_2 = "HNVDQHZHQ76PDA7VQ54HFFHIYNNYTHZWJSSQVKNWMIDTDPUH7ME5W6CKIE"

# ASA STATE OBSERVER
ASA_STATE_OBSERVER_APP_ID = 321230622

# TEST ASA STATE OBSERVER
TEST_ASA_STATE_OBSERVER_APP_ID = 24123396
