name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'

jobs:
  run-ci:

    name: Run Type Check & Linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.8

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2.2.0
        with:
          poetry-version: 1.1.13

      - name: Install python dependencies
        run: poetry install

      - uses: pre-commit/action@v3.0.0
        name: "Linters and formatters check"
        with:
          extra_args: --all-files --show-diff-on-failure
